# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Speech_Rep_Viewer_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(678, 564)
        self.SpCgRecList = QtWidgets.QListWidget(Dialog)
        self.SpCgRecList.setGeometry(QtCore.QRect(20, 310, 281, 211))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SpCgRecList.setFont(font)
        self.SpCgRecList.setObjectName("SpCgRecList")
        self.viewSpPdTnBtn = QtWidgets.QPushButton(Dialog)
        self.viewSpPdTnBtn.setGeometry(QtCore.QRect(303, 110, 65, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.viewSpPdTnBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("appRes/right.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewSpPdTnBtn.setIcon(icon)
        self.viewSpPdTnBtn.setObjectName("viewSpPdTnBtn")
        self.label_SpPdRep = QtWidgets.QLabel(Dialog)
        self.label_SpPdRep.setGeometry(QtCore.QRect(20, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SpPdRep.setFont(font)
        self.label_SpPdRep.setObjectName("label_SpPdRep")
        self.label_SpCgRep = QtWidgets.QLabel(Dialog)
        self.label_SpCgRep.setGeometry(QtCore.QRect(20, 290, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SpCgRep.setFont(font)
        self.label_SpCgRep.setObjectName("label_SpCgRep")
        self.viewSpCgTnBtn = QtWidgets.QPushButton(Dialog)
        self.viewSpCgTnBtn.setGeometry(QtCore.QRect(303, 393, 65, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.viewSpCgTnBtn.setFont(font)
        self.viewSpCgTnBtn.setIcon(icon)
        self.viewSpCgTnBtn.setObjectName("viewSpCgTnBtn")
        self.SpPdRecList = QtWidgets.QListWidget(Dialog)
        self.SpPdRecList.setGeometry(QtCore.QRect(20, 30, 281, 211))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SpPdRecList.setFont(font)
        self.SpPdRecList.setObjectName("SpPdRecList")
        self.SpPdTnList = QtWidgets.QListWidget(Dialog)
        self.SpPdTnList.setGeometry(QtCore.QRect(370, 30, 281, 211))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SpPdTnList.setFont(font)
        self.SpPdTnList.setObjectName("SpPdTnList")
        self.SpCgTnList = QtWidgets.QListWidget(Dialog)
        self.SpCgTnList.setGeometry(QtCore.QRect(370, 310, 281, 211))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SpCgTnList.setFont(font)
        self.SpCgTnList.setObjectName("SpCgTnList")
        self.label_SpPdTn = QtWidgets.QLabel(Dialog)
        self.label_SpPdTn.setGeometry(QtCore.QRect(370, 10, 500, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SpPdTn.setFont(font)
        self.label_SpPdTn.setObjectName("label_SpPdTn")
        self.label_SpCgTn = QtWidgets.QLabel(Dialog)
        self.label_SpCgTn.setGeometry(QtCore.QRect(370, 290, 500, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SpCgTn.setFont(font)
        self.label_SpCgTn.setObjectName("label_SpCgTn")
        self.viewResPD = QtWidgets.QPushButton(Dialog)
        self.viewResPD.setGeometry(QtCore.QRect(562, 250, 90, 23))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.viewResPD.setFont(font)
        self.viewResPD.setObjectName("viewResPD")
        self.viewResCG = QtWidgets.QPushButton(Dialog)
        self.viewResCG.setGeometry(QtCore.QRect(563, 530, 90, 23))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.viewResCG.setFont(font)
        self.viewResCG.setObjectName("viewResCG")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.viewSpPdTnBtn.setText(_translate("Dialog", "View\n"
"Tests"))
        self.label_SpPdRep.setText(_translate("Dialog", "PD Records:"))
        self.label_SpCgRep.setText(_translate("Dialog", "CG Records:"))
        self.viewSpCgTnBtn.setText(_translate("Dialog", "View\n"
"Tests"))
        self.label_SpPdTn.setText(_translate("Dialog", "PD Testnames of Selected Record:"))
        self.label_SpCgTn.setText(_translate("Dialog", "CG Testnames of Selected Record:"))
        self.viewResPD.setText(_translate("Dialog", "View Result.."))
        self.viewResCG.setText(_translate("Dialog", "View Result.."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
